version: "3.2"
services:
  pytigon:
    build: .
    image: pytigon:v1
    container_name: pytigon-container
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"

    extra_hosts:
        - "pytigon_db:db_serwer_ip"

    environment:
        - DATABASE_URL=mysql://user:password@pytigon_db/db_name
        - VIRTUAL_PORT=80
        #- PYTIGON_DEBUG=1
        - NO_EXECUTE_TASKS=1
        - INCLUDE_SETUP=True
        - INCLUDE_DEVTOOLS=True
        #- INCLUDE_PORTAL=True
        - MAIN_PRJ=schportal

    volumes:
      - type: "bind"
        source: "/var/log/pytigon"
        target: "/var/log"

      - type: "bind"
        source: "./app_pack"
        target: "/var/www/pytigon/app_pack"

      - www-data:/home/www-data/.pytigon

volumes:
  www-data:
